"""Add category and owner_id to images

Revision ID: 37ee98d9f206
Revises: 051c882027ee
Create Date: 2025-07-05 18:10:24.178279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37ee98d9f206'
down_revision: Union[str, Sequence[str], None] = '051c882027ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('category', sa.String(), nullable=True))
    op.add_column('images', sa.Column('owner_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'category')
    op.drop_column('images', 'owner_id')
    # ### end Alembic commands ###
